---
title: "aircraft-pfp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{aircraft-pfp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rtorf)
library(data.table)
```


```{r read1, eval = T}

cate = c("aircraft-pfp",
         "aircraft-insitu",
         "aircraft-flask",
         "surface-insitu",
         "surface-flask", 
         "surface-pfp",   
         "tower-insitu",  
         "aircore",       
         "shipboard-insitu",
         "shipboard-flask") 

obs <- "Z:/torf/obspack_ch4_1_GLOBALVIEWplus_v5.1_2023-03-08/data/nc/"
index <- obs_summary(obs = obs, 
                     categories = cate)

```

Now we read the aircraft-pfp using the function `obs_read_nc`. To this date,
solar_time is not included for aircrafts, so `FALSE` that argument.

```{r}
df <- obs_read_nc(index = index,
                  categories = "aircraft-pfp",
                  solar_time = FALSE,
                  verbose = T)

format(object.size(df), unit = "Gb")
```

